# api-spec.yaml
openapi: 3.0.0
servers:
  - description: Localhost
    url: http://127.0.0.1:5762
info:
  description: 
  version: 1.0.0
  title: Causality Assessment Tool
  contact:
    name: "API Support"
    url: "http://www.example.com/support"
    email: "support@example.com"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /eval_causality:
    post:
      summary: Evaluates causality level based on data given
      description: |
        Pass a feature list to the model and returns the probabilities for causality assessment
      parameters:
      requestBody:
        description: Data already known beforehand
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputData'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CausalityEvaluation'

        405:
          description: Method Not Allowed
          content: 
            'application/json': {}
            'application/xml': {}
components:
  schemas:
    InputData:
      type: object
      properties:
        DESCRIBED:
          description: "DESCRIBED"
          type: string
          enum:
           - "No"
           - "Yes"
        REINTRODUCED:
          description: "REINTRODUCED"
          type: string
          enum:
           - "No"
           - "Yes"
        REAPPEARED:
          description: "REAPPEARED AFTER REINTRODUCTION"
          type: string
          enum:
           - "No"
           - "Yes"
           - "Not Reintroduced"
        ADMINISTRATION:
          description: "ADMINISTRATION"
          type: string
          enum:
           - "Oral"
           - "Injectable"
           - "Topical"
        NOTIFIER:
          description: "REPORTER"
          type: string
          enum:
           - "Physician"
           - "Nurse"
           - "Pharmacist"
        SUSPENDED:
          description: "SUSPENDED"
          type: string
          enum:
           - "No"
           - "Yes"
           - "Reduced"
        IMPROVED:
          description: "IMPROVED AFTER SUSPENSION"
          type: string
          enum:
           - "No"
           - "Yes"
           - "Not Suspended"
        CONCOMITANT:
          description: "CONCOMITANT DRUGS"
          type: string
          enum:
           - "No"
           - "Yes"
        INTERACT:
          description: "SUSPISCION OF INTERACTION"
          type: string
          enum:
           - "No"
           - "Yes"
        INEFFECTIVE:
          description: "DRUG INEFFECTIVENESS"
          type: string
          enum:
           - "No"
           - "Yes" 
        PHARMAGROUP:
          description: "PHARMACOTHERAPEUTIC GROUP"
          type: string
          enum:
           - "Drugs for Skin Disorders"
           - "Drugs for Eve Disorders"
           - "Antiallergic Medication"
           - "Antinfectious"
           - "Antineoplastic Drugs & Immunemodulators"
           - "Cardiovascular System"
           - "Gastrointestinal System"
           - "Genitourinary System"
           - "Locomotor System"
           - "Respiratory System"
           - "Hormones"
           - "Diagnosis Media"
           - "Nutrition"
           - "Blood"
           - "Central Nervous System"
           - "Drugs to Treat Poisoning"
           - "Vaccines & Immunoglobulins"

    GeneralError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string


    CausalityEvaluation:
      type: object
      properties:
        definitve_score:
          type: integer
          format: float
        probable_score:
          type: integer
          format: float
        possible_score:
          type: integer
          format: float
        conditional_score:
          type: integer
          format: float